### ISSUE TITLE
Error installing GenSVM

### ISSUE THREAD

**Issue by Dr4cky** [GjjvdBurg/PyGenSVM#11]
I tried to install the package, but encountered the following error (the error is larger, this is only a section. I can attach the entire error if needed). I tried to install the package across different laptops, but the same issue occurs.  I tried $ pip install numpy && pip install gensvm as well as $ pip install gensvm.

Thank you!

> Collecting gensvm
>     ERROR: Command errored out with exit status 1:
>      command: 'C:\Users\USER\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\2\\pip-install-k2yboajk\\gensvm_1fc99d4f45454cd9a08d64a952191cb9\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\2\\pip-install-k2yboajk\\gensvm_1fc99d4f45454cd9a08d64a952191cb9\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\USER\AppData\Local\Temp\2\pip-pip-egg-info-d1ys9viq'
>          cwd: C:\Users\USER\AppData\Local\Temp\2\pip-install-k2yboajk\gensvm_1fc99d4f45454cd9a08d64a952191cb9\
>     Complete output (49 lines):
>     Could not locate executable g77
>     Could not locate executable f77
>     Could not locate executable ifort
>     Could not locate executable ifl
>     Could not locate executable f90
>     Could not locate executable DF
>     Could not locate executable efl
>     Could not locate executable gfortran
>     Could not locate executable f95
>     Could not locate executable g95
>     Could not locate executable efort
>     Could not locate executable efc
>     Could not locate executable flang
>     don't know how to compile Fortran code on platform 'nt'
>     C:\Users\USER\Anaconda3\lib\site-packages\numpy\distutils\system_info.py:1989: UserWarning:
>         Optimized (vendor) Blas libraries are not found.
>         Falls back to netlib Blas library which has worse performance.
>         A better performance should be easily gained by switching
>         Blas library.
>       if self._calc_info(blas):
>     C:\Users\USER\Anaconda3\lib\site-packages\numpy\distutils\system_info.py:1989: UserWarning:
>         Blas (http://www.netlib.org/blas/) libraries not found.
>         Directories to search for the libraries can be specified in the
>         numpy/distutils/site.cfg file (section [blas]) or by setting
>         the BLAS environment variable.
>       if self._calc_info(blas):
>     C:\Users\USER\Anaconda3\lib\site-packages\numpy\distutils\system_info.py:1989: UserWarning:
>         Blas (http://www.netlib.org/blas/) sources not found.
>         Directories to search for the sources can be specified in the
>         numpy/distutils/site.cfg file (section [blas_src]) or by setting
>         the BLAS_SRC environment variable.
>       if self._calc_info(blas):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\USER\AppData\Local\Temp\2\pip-install-k2yboajk\gensvm_1fc99d4f45454cd9a08d64a952191cb9\setup.py", line 348, in <module>
>         attr = configuration().todict()
>       File "C:\Users\USER\AppData\Local\Temp\2\pip-install-k2yboajk\gensvm_1fc99d4f45454cd9a08d64a952191cb9\setup.py", line 253, in configuration
>         cblas_libs, blas_info = _skl_get_blas_info()
>       File "C:\Users\USER\AppData\Local\Temp\2\pip-install-k2yboajk\gensvm_1fc99d4f45454cd9a08d64a952191cb9\setup.py", line 164, in _skl_get_blas_info
>         blas_info = get_info("blas_opt", notfound_action=2)
>       File "C:\Users\USER\Anaconda3\lib\site-packages\numpy\distutils\system_info.py", line 584, in get_info
>         return cl().get_info(notfound_action)
>       File "C:\Users\USER\Anaconda3\lib\site-packages\numpy\distutils\system_info.py", line 850, in get_info
>         raise self.notfounderror(self.notfounderror.__doc__)
>     numpy.distutils.system_info.BlasNotFoundError:
>         Blas (http://www.netlib.org/blas/) libraries not found.
>         Directories to search for the libraries can be specified in the
>         numpy/distutils/site.cfg file (section [blas]) or by setting
>         the BLAS environment variable.
>

**Comment by GjjvdBurg** [comment]
Thanks for letting me know about this @Dr4cky! I'll look into this as soon as I can. In the meantime, perhaps the [R package](https://github.com/GjjvdBurg/RGenSVM) for GenSVM can be useful to you.

**Comment by Dr4cky** [comment]
No problem, thanks for your response. Attached you'll find the full error log, probably more useful than what I have already posted.

[GenSVM error.docx](https://github.com/GjjvdBurg/PyGenSVM/files/6919532/GenSVM.error.docx)

**Comment by GjjvdBurg** [comment]
Thanks for the detailed log @Dr4cky, much appreciated!
